# Generated by Django 4.2 on 2025-02-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Residents_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resident_id", models.CharField(max_length=15, unique=True)),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=12)),
                ("house_id", models.CharField(max_length=12)),
                ("gender", models.CharField(max_length=12)),
            ],
            options={
                "db_table": "resident_table",
            },
        ),
    ]
