# Generated by Django 5.2 on 2026-03-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a2_resident_function", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=150)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "pending"),
                            ("Approve", "Approve"),
                            ("Rejected", "rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "service_table",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResidentServiceAvail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a2_resident_function.residents_model",
                    ),
                ),
                (
                    "service_avail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a3_services_function.service_model",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permit_mode",
            fields=[
                ("permit_id", models.AutoField(primary_key=True, serialize=False)),
                ("application_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "pending"),
                            ("Approve", "Approve"),
                            ("Rejected", "rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "resident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a2_resident_function.residents_model",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a3_services_function.service_model",
                    ),
                ),
            ],
            options={
                "db_table": "permits_table",
                "ordering": ["-created_at"],
            },
        ),
    ]
