# Generated by Django 5.2 on 2025-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("expiry", models.DateField()),
                ("remark", models.TextField(blank=True)),
            ],
        ),
    ]
