# Generated by Django 5.2 on 2025-09-14 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical_function", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Medicine",
            new_name="Medicine_model",
        ),
        migrations.RenameField(
            model_name="medicine_model",
            old_name="expiry",
            new_name="expiry_date",
        ),
    ]
