# Generated by Django 4.2 on 2025-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "announcement_table",
            },
        ),
    ]
