# Generated by Django 4.2 on 2025-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annoucement_function", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("published_date", models.DateField(auto_now_add=True)),
                ("expiry_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
    ]
