# Generated by Django 4.2 on 2025-02-27 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("annoucement_function", "0002_announcement_model_delete_announcement"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="announcement_model",
            table="announcement_table",
        ),
    ]
