# Generated by Django 4.2 on 2025-03-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resident_function", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints_model",
            fields=[
                ("complaint_id", models.AutoField(primary_key=True, serialize=False)),
                ("complaint_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "pending"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "resolved"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("archive", models.BooleanField(default=False)),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resident_function.residents_model",
                    ),
                ),
            ],
            options={
                "db_table": "complaints_table",
            },
        ),
    ]
