# Generated by Django 4.2 on 2025-02-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resident_function", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service_model",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=150)),
                ("fee", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "db_table": "service_table",
            },
        ),
        migrations.CreateModel(
            name="Permit_mode",
            fields=[
                ("permit_id", models.AutoField(primary_key=True, serialize=False)),
                ("application_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "pending"),
                            ("Approve", "Approve"),
                            ("Rejected", "rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "resident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resident_function.residents_model",
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_function.service_model",
                    ),
                ),
            ],
            options={
                "db_table": "permits_table",
            },
        ),
    ]
