# Generated by Django 4.2 on 2025-02-27 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("resident_function", "0001_initial"),
        ("services_function", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResidentServiceAvail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resident_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resident_function.residents_model",
                    ),
                ),
                (
                    "service_avail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services_function.service_model",
                    ),
                ),
            ],
        ),
    ]
